/* 389. Find the Difference

# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.*/


    char findTheDifference(string s, string t) {
        vector<int> vec(26,0);
        //vector<int> vec(26,0):定义26个整型元素的向量，并赋初始值为0
        for(int i = 0;i<s.size();i++){
            vec[s[i]-'a']++;
            //s[i]-'a'的值是s[i]这个字母与字母表第一个字母'a'的差值，差0为a,s差1为b...
        }
        for(int i = 0;i<t.size();i++){
            if(vec[t[i]-'a'] != 0) vec[t[i]-'a']--;
            //如果在向量中t[i]这个字母已经存在，t[i]对应的这个字母在向量中的数值减一（即，重复出现的第一次就把他删掉）
            else return t[i];
            //如果在向量中t[i]这个字母不存在，输出
        }
        return 'a';
    }
